// Copyright 2017 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by gen-accessors; DO NOT EDIT.
package bitbucket

import (
	"time"
)

// GetDownloadCount returns the DownloadCount field if it's non-nil, zero value otherwise.
func (a *Artifact) GetDownloadCount() int64 {
	if a == nil || a.DownloadCount == nil {
		return 0
	}
	return *a.DownloadCount
}

// GetLinks returns the Links field.
func (a *Artifact) GetLinks() *ArtifactFileLinks {
	if a == nil {
		return nil
	}
	return a.Links
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (a *Artifact) GetName() string {
	if a == nil || a.Name == nil {
		return ""
	}
	return *a.Name
}

// GetSize returns the Size field if it's non-nil, zero value otherwise.
func (a *Artifact) GetSize() int64 {
	if a == nil || a.Size == nil {
		return 0
	}
	return *a.Size
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (a *Artifact) GetType() string {
	if a == nil || a.Type == nil {
		return ""
	}
	return *a.Type
}

// GetUser returns the User field.
func (a *Artifact) GetUser() *User {
	if a == nil {
		return nil
	}
	return a.User
}

// GetSelf returns the Self field.
func (a *ArtifactFileLinks) GetSelf() *Link {
	if a == nil {
		return nil
	}
	return a.Self
}

// GetBranch returns the Branch field.
func (b *BMBranch) GetBranch() *Ref {
	if b == nil {
		return nil
	}
	return b.Branch
}

// GetIsValid returns the IsValid field if it's non-nil, zero value otherwise.
func (b *BMBranch) GetIsValid() bool {
	if b == nil || b.IsValid == nil {
		return false
	}
	return *b.IsValid
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (b *BMBranch) GetName() string {
	if b == nil || b.Name == nil {
		return ""
	}
	return *b.Name
}

// GetUseMainbranch returns the UseMainbranch field if it's non-nil, zero value otherwise.
func (b *BMBranch) GetUseMainbranch() bool {
	if b == nil || b.UseMainbranch == nil {
		return false
	}
	return *b.UseMainbranch
}

// GetEnabled returns the Enabled field if it's non-nil, zero value otherwise.
func (b *BMBranchTypes) GetEnabled() bool {
	if b == nil || b.Enabled == nil {
		return false
	}
	return *b.Enabled
}

// GetKind returns the Kind field if it's non-nil, zero value otherwise.
func (b *BMBranchTypes) GetKind() string {
	if b == nil || b.Kind == nil {
		return ""
	}
	return *b.Kind
}

// GetPrefix returns the Prefix field if it's non-nil, zero value otherwise.
func (b *BMBranchTypes) GetPrefix() string {
	if b == nil || b.Prefix == nil {
		return ""
	}
	return *b.Prefix
}

// GetEnabled returns the Enabled field if it's non-nil, zero value otherwise.
func (b *BMBranchUpdateOpts) GetEnabled() bool {
	if b == nil || b.Enabled == nil {
		return false
	}
	return *b.Enabled
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (b *BMBranchUpdateOpts) GetName() string {
	if b == nil || b.Name == nil {
		return ""
	}
	return *b.Name
}

// GetUseMainbranch returns the UseMainbranch field if it's non-nil, zero value otherwise.
func (b *BMBranchUpdateOpts) GetUseMainbranch() bool {
	if b == nil || b.UseMainbranch == nil {
		return false
	}
	return *b.UseMainbranch
}

// GetSelf returns the Self field.
func (b *BMLinks) GetSelf() *Link {
	if b == nil {
		return nil
	}
	return b.Self
}

// GetDevelopment returns the Development field.
func (b *BMRequest) GetDevelopment() *BMBranchUpdateOpts {
	if b == nil {
		return nil
	}
	return b.Development
}

// GetProduction returns the Production field.
func (b *BMRequest) GetProduction() *BMBranchUpdateOpts {
	if b == nil {
		return nil
	}
	return b.Production
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (b *Branch) GetName() string {
	if b == nil || b.Name == nil {
		return ""
	}
	return *b.Name
}

// GetDevelopment returns the Development field.
func (b *BranchingModel) GetDevelopment() *BMBranch {
	if b == nil {
		return nil
	}
	return b.Development
}

// GetLinks returns the Links field.
func (b *BranchingModel) GetLinks() *BMLinks {
	if b == nil {
		return nil
	}
	return b.Links
}

// GetProduction returns the Production field.
func (b *BranchingModel) GetProduction() *BMBranch {
	if b == nil {
		return nil
	}
	return b.Production
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (b *BranchingModel) GetType() string {
	if b == nil || b.Type == nil {
		return ""
	}
	return *b.Type
}

// GetBranchMatchKind returns the BranchMatchKind field if it's non-nil, zero value otherwise.
func (b *BranchRestriction) GetBranchMatchKind() string {
	if b == nil || b.BranchMatchKind == nil {
		return ""
	}
	return *b.BranchMatchKind
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (b *BranchRestriction) GetID() int64 {
	if b == nil || b.ID == nil {
		return 0
	}
	return *b.ID
}

// GetKind returns the Kind field if it's non-nil, zero value otherwise.
func (b *BranchRestriction) GetKind() string {
	if b == nil || b.Kind == nil {
		return ""
	}
	return *b.Kind
}

// GetLinks returns the Links field.
func (b *BranchRestriction) GetLinks() *BRLinks {
	if b == nil {
		return nil
	}
	return b.Links
}

// GetPattern returns the Pattern field if it's non-nil, zero value otherwise.
func (b *BranchRestriction) GetPattern() string {
	if b == nil || b.Pattern == nil {
		return ""
	}
	return *b.Pattern
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (b *BranchRestriction) GetType() string {
	if b == nil || b.Type == nil {
		return ""
	}
	return *b.Type
}

// GetValue returns the Value field if it's non-nil, zero value otherwise.
func (b *BranchRestriction) GetValue() int64 {
	if b == nil || b.Value == nil {
		return 0
	}
	return *b.Value
}

// GetSelf returns the Self field.
func (b *BRLinks) GetSelf() *Link {
	if b == nil {
		return nil
	}
	return b.Self
}

// GetBranchMatchKind returns the BranchMatchKind field if it's non-nil, zero value otherwise.
func (b *BRRequest) GetBranchMatchKind() string {
	if b == nil || b.BranchMatchKind == nil {
		return ""
	}
	return *b.BranchMatchKind
}

// GetBranchType returns the BranchType field if it's non-nil, zero value otherwise.
func (b *BRRequest) GetBranchType() string {
	if b == nil || b.BranchType == nil {
		return ""
	}
	return *b.BranchType
}

// GetKind returns the Kind field if it's non-nil, zero value otherwise.
func (b *BRRequest) GetKind() string {
	if b == nil || b.Kind == nil {
		return ""
	}
	return *b.Kind
}

// GetPattern returns the Pattern field if it's non-nil, zero value otherwise.
func (b *BRRequest) GetPattern() string {
	if b == nil || b.Pattern == nil {
		return ""
	}
	return *b.Pattern
}

// GetHTML returns the HTML field.
func (c *CCLinks) GetHTML() *Link {
	if c == nil {
		return nil
	}
	return c.HTML
}

// GetSelf returns the Self field.
func (c *CCLinks) GetSelf() *Link {
	if c == nil {
		return nil
	}
	return c.Self
}

// GetLinks returns the Links field.
func (c *CodeFile) GetLinks() *SearchCodeFileLinks {
	if c == nil {
		return nil
	}
	return c.Links
}

// GetPath returns the Path field if it's non-nil, zero value otherwise.
func (c *CodeFile) GetPath() string {
	if c == nil || c.Path == nil {
		return ""
	}
	return *c.Path
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (c *CodeFile) GetType() string {
	if c == nil || c.Type == nil {
		return ""
	}
	return *c.Type
}

// GetContent returns the Content field.
func (c *Comment) GetContent() *Content {
	if c == nil {
		return nil
	}
	return c.Content
}

// GetCreatedOn returns the CreatedOn field if it's non-nil, zero value otherwise.
func (c *Comment) GetCreatedOn() time.Time {
	if c == nil || c.CreatedOn == nil {
		return time.Time{}
	}
	return *c.CreatedOn
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (c *Comment) GetID() int64 {
	if c == nil || c.ID == nil {
		return 0
	}
	return *c.ID
}

// GetLinks returns the Links field.
func (c *Comment) GetLinks() *CommentLinks {
	if c == nil {
		return nil
	}
	return c.Links
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (c *Comment) GetType() string {
	if c == nil || c.Type == nil {
		return ""
	}
	return *c.Type
}

// GetUpdatedOn returns the UpdatedOn field if it's non-nil, zero value otherwise.
func (c *Comment) GetUpdatedOn() time.Time {
	if c == nil || c.UpdatedOn == nil {
		return time.Time{}
	}
	return *c.UpdatedOn
}

// GetUser returns the User field.
func (c *Comment) GetUser() *User {
	if c == nil {
		return nil
	}
	return c.User
}

// GetHTML returns the HTML field.
func (c *CommentLinks) GetHTML() *Link {
	if c == nil {
		return nil
	}
	return c.HTML
}

// GetSelf returns the Self field.
func (c *CommentLinks) GetSelf() *Link {
	if c == nil {
		return nil
	}
	return c.Self
}

// GetAuthor returns the Author field.
func (c *Commit) GetAuthor() *User {
	if c == nil {
		return nil
	}
	return c.Author
}

// GetDate returns the Date field if it's non-nil, zero value otherwise.
func (c *Commit) GetDate() time.Time {
	if c == nil || c.Date == nil {
		return time.Time{}
	}
	return *c.Date
}

// GetHash returns the Hash field if it's non-nil, zero value otherwise.
func (c *Commit) GetHash() string {
	if c == nil || c.Hash == nil {
		return ""
	}
	return *c.Hash
}

// GetLinks returns the Links field.
func (c *Commit) GetLinks() *CommitLinks {
	if c == nil {
		return nil
	}
	return c.Links
}

// GetMessage returns the Message field if it's non-nil, zero value otherwise.
func (c *Commit) GetMessage() string {
	if c == nil || c.Message == nil {
		return ""
	}
	return *c.Message
}

// GetRendered returns the Rendered field.
func (c *Commit) GetRendered() *CommitMessageContent {
	if c == nil {
		return nil
	}
	return c.Rendered
}

// GetRepository returns the Repository field.
func (c *Commit) GetRepository() *Repository {
	if c == nil {
		return nil
	}
	return c.Repository
}

// GetSummary returns the Summary field.
func (c *Commit) GetSummary() *Content {
	if c == nil {
		return nil
	}
	return c.Summary
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (c *Commit) GetType() string {
	if c == nil || c.Type == nil {
		return ""
	}
	return *c.Type
}

// GetCommit returns the Commit field.
func (c *CommitComment) GetCommit() *Commit {
	if c == nil {
		return nil
	}
	return c.Commit
}

// GetContent returns the Content field.
func (c *CommitComment) GetContent() *Content {
	if c == nil {
		return nil
	}
	return c.Content
}

// GetCreatedOn returns the CreatedOn field if it's non-nil, zero value otherwise.
func (c *CommitComment) GetCreatedOn() time.Time {
	if c == nil || c.CreatedOn == nil {
		return time.Time{}
	}
	return *c.CreatedOn
}

// GetDeleted returns the Deleted field if it's non-nil, zero value otherwise.
func (c *CommitComment) GetDeleted() bool {
	if c == nil || c.Deleted == nil {
		return false
	}
	return *c.Deleted
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (c *CommitComment) GetID() int64 {
	if c == nil || c.ID == nil {
		return 0
	}
	return *c.ID
}

// GetLinks returns the Links field.
func (c *CommitComment) GetLinks() *CCLinks {
	if c == nil {
		return nil
	}
	return c.Links
}

// GetParent returns the Parent field.
func (c *CommitComment) GetParent() *CommitComment {
	if c == nil {
		return nil
	}
	return c.Parent
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (c *CommitComment) GetType() string {
	if c == nil || c.Type == nil {
		return ""
	}
	return *c.Type
}

// GetUpdatedOn returns the UpdatedOn field if it's non-nil, zero value otherwise.
func (c *CommitComment) GetUpdatedOn() time.Time {
	if c == nil || c.UpdatedOn == nil {
		return time.Time{}
	}
	return *c.UpdatedOn
}

// GetUser returns the User field.
func (c *CommitComment) GetUser() *User {
	if c == nil {
		return nil
	}
	return c.User
}

// GetContent returns the Content field.
func (c *CommitCommentRequest) GetContent() *Content {
	if c == nil {
		return nil
	}
	return c.Content
}

// GetParentComment returns the ParentComment field.
func (c *CommitCommentRequest) GetParentComment() *CommitComment {
	if c == nil {
		return nil
	}
	return c.ParentComment
}

// GetApprove returns the Approve field.
func (c *CommitLinks) GetApprove() *Link {
	if c == nil {
		return nil
	}
	return c.Approve
}

// GetComment returns the Comment field.
func (c *CommitLinks) GetComment() *Link {
	if c == nil {
		return nil
	}
	return c.Comment
}

// GetDiff returns the Diff field.
func (c *CommitLinks) GetDiff() *Link {
	if c == nil {
		return nil
	}
	return c.Diff
}

// GetHTML returns the HTML field.
func (c *CommitLinks) GetHTML() *Link {
	if c == nil {
		return nil
	}
	return c.HTML
}

// GetSelf returns the Self field.
func (c *CommitLinks) GetSelf() *Link {
	if c == nil {
		return nil
	}
	return c.Self
}

// GetStatuses returns the Statuses field.
func (c *CommitLinks) GetStatuses() *Link {
	if c == nil {
		return nil
	}
	return c.Statuses
}

// GetMessage returns the Message field.
func (c *CommitMessageContent) GetMessage() *Content {
	if c == nil {
		return nil
	}
	return c.Message
}

// GetCreatedOn returns the CreatedOn field if it's non-nil, zero value otherwise.
func (c *CommitStatus) GetCreatedOn() time.Time {
	if c == nil || c.CreatedOn == nil {
		return time.Time{}
	}
	return *c.CreatedOn
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (c *CommitStatus) GetDescription() string {
	if c == nil || c.Description == nil {
		return ""
	}
	return *c.Description
}

// GetKey returns the Key field if it's non-nil, zero value otherwise.
func (c *CommitStatus) GetKey() string {
	if c == nil || c.Key == nil {
		return ""
	}
	return *c.Key
}

// GetLinks returns the Links field.
func (c *CommitStatus) GetLinks() *CSLinks {
	if c == nil {
		return nil
	}
	return c.Links
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (c *CommitStatus) GetName() string {
	if c == nil || c.Name == nil {
		return ""
	}
	return *c.Name
}

// GetRefname returns the Refname field if it's non-nil, zero value otherwise.
func (c *CommitStatus) GetRefname() string {
	if c == nil || c.Refname == nil {
		return ""
	}
	return *c.Refname
}

// GetState returns the State field if it's non-nil, zero value otherwise.
func (c *CommitStatus) GetState() string {
	if c == nil || c.State == nil {
		return ""
	}
	return *c.State
}

// GetUpdatedOn returns the UpdatedOn field if it's non-nil, zero value otherwise.
func (c *CommitStatus) GetUpdatedOn() time.Time {
	if c == nil || c.UpdatedOn == nil {
		return time.Time{}
	}
	return *c.UpdatedOn
}

// GetURL returns the URL field if it's non-nil, zero value otherwise.
func (c *CommitStatus) GetURL() string {
	if c == nil || c.URL == nil {
		return ""
	}
	return *c.URL
}

// GetUUID returns the UUID field if it's non-nil, zero value otherwise.
func (c *CommitStatus) GetUUID() string {
	if c == nil || c.UUID == nil {
		return ""
	}
	return *c.UUID
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (c *CommitStatusRequest) GetDescription() string {
	if c == nil || c.Description == nil {
		return ""
	}
	return *c.Description
}

// GetKey returns the Key field if it's non-nil, zero value otherwise.
func (c *CommitStatusRequest) GetKey() string {
	if c == nil || c.Key == nil {
		return ""
	}
	return *c.Key
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (c *CommitStatusRequest) GetName() string {
	if c == nil || c.Name == nil {
		return ""
	}
	return *c.Name
}

// GetRefname returns the Refname field if it's non-nil, zero value otherwise.
func (c *CommitStatusRequest) GetRefname() string {
	if c == nil || c.Refname == nil {
		return ""
	}
	return *c.Refname
}

// GetState returns the State field if it's non-nil, zero value otherwise.
func (c *CommitStatusRequest) GetState() string {
	if c == nil || c.State == nil {
		return ""
	}
	return *c.State
}

// GetURL returns the URL field if it's non-nil, zero value otherwise.
func (c *CommitStatusRequest) GetURL() string {
	if c == nil || c.URL == nil {
		return ""
	}
	return *c.URL
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (c *Component) GetID() int64 {
	if c == nil || c.ID == nil {
		return 0
	}
	return *c.ID
}

// GetLinks returns the Links field.
func (c *Component) GetLinks() *ComponentLinks {
	if c == nil {
		return nil
	}
	return c.Links
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (c *Component) GetName() string {
	if c == nil || c.Name == nil {
		return ""
	}
	return *c.Name
}

// GetRepository returns the Repository field.
func (c *Component) GetRepository() *Repository {
	if c == nil {
		return nil
	}
	return c.Repository
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (c *Component) GetType() string {
	if c == nil || c.Type == nil {
		return ""
	}
	return *c.Type
}

// GetSelf returns the Self field.
func (c *ComponentLinks) GetSelf() *Link {
	if c == nil {
		return nil
	}
	return c.Self
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (c *ComponentRequest) GetName() string {
	if c == nil || c.Name == nil {
		return ""
	}
	return *c.Name
}

// GetHTML returns the HTML field if it's non-nil, zero value otherwise.
func (c *Content) GetHTML() string {
	if c == nil || c.HTML == nil {
		return ""
	}
	return *c.HTML
}

// GetMarkup returns the Markup field if it's non-nil, zero value otherwise.
func (c *Content) GetMarkup() string {
	if c == nil || c.Markup == nil {
		return ""
	}
	return *c.Markup
}

// GetRaw returns the Raw field if it's non-nil, zero value otherwise.
func (c *Content) GetRaw() string {
	if c == nil || c.Raw == nil {
		return ""
	}
	return *c.Raw
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (c *Content) GetType() string {
	if c == nil || c.Type == nil {
		return ""
	}
	return *c.Type
}

// GetHTML returns the HTML field.
func (c *CSLinks) GetHTML() *Link {
	if c == nil {
		return nil
	}
	return c.HTML
}

// GetSelf returns the Self field.
func (c *CSLinks) GetSelf() *Link {
	if c == nil {
		return nil
	}
	return c.Self
}

// GetAddedOn returns the AddedOn field if it's non-nil, zero value otherwise.
func (d *DeployKey) GetAddedOn() time.Time {
	if d == nil || d.AddedOn == nil {
		return time.Time{}
	}
	return *d.AddedOn
}

// GetComment returns the Comment field if it's non-nil, zero value otherwise.
func (d *DeployKey) GetComment() string {
	if d == nil || d.Comment == nil {
		return ""
	}
	return *d.Comment
}

// GetCreatedOn returns the CreatedOn field if it's non-nil, zero value otherwise.
func (d *DeployKey) GetCreatedOn() time.Time {
	if d == nil || d.CreatedOn == nil {
		return time.Time{}
	}
	return *d.CreatedOn
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (d *DeployKey) GetID() int64 {
	if d == nil || d.ID == nil {
		return 0
	}
	return *d.ID
}

// GetKey returns the Key field if it's non-nil, zero value otherwise.
func (d *DeployKey) GetKey() string {
	if d == nil || d.Key == nil {
		return ""
	}
	return *d.Key
}

// GetLabel returns the Label field if it's non-nil, zero value otherwise.
func (d *DeployKey) GetLabel() string {
	if d == nil || d.Label == nil {
		return ""
	}
	return *d.Label
}

// GetLastUsed returns the LastUsed field if it's non-nil, zero value otherwise.
func (d *DeployKey) GetLastUsed() time.Time {
	if d == nil || d.LastUsed == nil {
		return time.Time{}
	}
	return *d.LastUsed
}

// GetLinks returns the Links field.
func (d *DeployKey) GetLinks() *DeployKeyLinks {
	if d == nil {
		return nil
	}
	return d.Links
}

// GetRepository returns the Repository field.
func (d *DeployKey) GetRepository() *Repository {
	if d == nil {
		return nil
	}
	return d.Repository
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (d *DeployKey) GetType() string {
	if d == nil || d.Type == nil {
		return ""
	}
	return *d.Type
}

// GetSelf returns the Self field.
func (d *DeployKeyLinks) GetSelf() *Link {
	if d == nil {
		return nil
	}
	return d.Self
}

// GetKey returns the Key field if it's non-nil, zero value otherwise.
func (d *DeployKeyRequest) GetKey() string {
	if d == nil || d.Key == nil {
		return ""
	}
	return *d.Key
}

// GetLabel returns the Label field if it's non-nil, zero value otherwise.
func (d *DeployKeyRequest) GetLabel() string {
	if d == nil || d.Label == nil {
		return ""
	}
	return *d.Label
}

// GetLinesAdded returns the LinesAdded field if it's non-nil, zero value otherwise.
func (d *Diff) GetLinesAdded() int64 {
	if d == nil || d.LinesAdded == nil {
		return 0
	}
	return *d.LinesAdded
}

// GetLinesRemoved returns the LinesRemoved field if it's non-nil, zero value otherwise.
func (d *Diff) GetLinesRemoved() int64 {
	if d == nil || d.LinesRemoved == nil {
		return 0
	}
	return *d.LinesRemoved
}

// GetNew returns the New field.
func (d *Diff) GetNew() *CodeFile {
	if d == nil {
		return nil
	}
	return d.New
}

// GetOld returns the Old field.
func (d *Diff) GetOld() *CodeFile {
	if d == nil {
		return nil
	}
	return d.Old
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (d *Diff) GetStatus() string {
	if d == nil || d.Status == nil {
		return ""
	}
	return *d.Status
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (d *Diff) GetType() string {
	if d == nil || d.Type == nil {
		return ""
	}
	return *d.Type
}

// GetBinary returns the Binary field if it's non-nil, zero value otherwise.
func (d *DiffGetOpts) GetBinary() string {
	if d == nil || d.Binary == nil {
		return ""
	}
	return *d.Binary
}

// GetContext returns the Context field if it's non-nil, zero value otherwise.
func (d *DiffGetOpts) GetContext() int {
	if d == nil || d.Context == nil {
		return 0
	}
	return *d.Context
}

// GetIgnoreWhitespace returns the IgnoreWhitespace field if it's non-nil, zero value otherwise.
func (d *DiffGetOpts) GetIgnoreWhitespace() string {
	if d == nil || d.IgnoreWhitespace == nil {
		return ""
	}
	return *d.IgnoreWhitespace
}

// GetPath returns the Path field if it's non-nil, zero value otherwise.
func (d *DiffGetOpts) GetPath() string {
	if d == nil || d.Path == nil {
		return ""
	}
	return *d.Path
}

// GetHistory returns the History field.
func (f *FileHistoryLinks) GetHistory() *Link {
	if f == nil {
		return nil
	}
	return f.History
}

// GetMeta returns the Meta field.
func (f *FileHistoryLinks) GetMeta() *Link {
	if f == nil {
		return nil
	}
	return f.Meta
}

// GetSelf returns the Self field.
func (f *FileHistoryLinks) GetSelf() *Link {
	if f == nil {
		return nil
	}
	return f.Self
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (f *ForkRequest) GetDescription() string {
	if f == nil || f.Description == nil {
		return ""
	}
	return *f.Description
}

// GetForkPolicy returns the ForkPolicy field if it's non-nil, zero value otherwise.
func (f *ForkRequest) GetForkPolicy() string {
	if f == nil || f.ForkPolicy == nil {
		return ""
	}
	return *f.ForkPolicy
}

// GetHasIssues returns the HasIssues field if it's non-nil, zero value otherwise.
func (f *ForkRequest) GetHasIssues() string {
	if f == nil || f.HasIssues == nil {
		return ""
	}
	return *f.HasIssues
}

// GetHasWiki returns the HasWiki field if it's non-nil, zero value otherwise.
func (f *ForkRequest) GetHasWiki() bool {
	if f == nil || f.HasWiki == nil {
		return false
	}
	return *f.HasWiki
}

// GetIsPrivate returns the IsPrivate field if it's non-nil, zero value otherwise.
func (f *ForkRequest) GetIsPrivate() bool {
	if f == nil || f.IsPrivate == nil {
		return false
	}
	return *f.IsPrivate
}

// GetLanguage returns the Language field if it's non-nil, zero value otherwise.
func (f *ForkRequest) GetLanguage() string {
	if f == nil || f.Language == nil {
		return ""
	}
	return *f.Language
}

// GetMainBranch returns the MainBranch field.
func (f *ForkRequest) GetMainBranch() *RepositoryMainBranch {
	if f == nil {
		return nil
	}
	return f.MainBranch
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (f *ForkRequest) GetName() string {
	if f == nil || f.Name == nil {
		return ""
	}
	return *f.Name
}

// GetOwner returns the Owner field.
func (f *ForkRequest) GetOwner() *User {
	if f == nil {
		return nil
	}
	return f.Owner
}

// GetParent returns the Parent field.
func (f *ForkRequest) GetParent() *Repository {
	if f == nil {
		return nil
	}
	return f.Parent
}

// GetSCM returns the SCM field if it's non-nil, zero value otherwise.
func (f *ForkRequest) GetSCM() string {
	if f == nil || f.SCM == nil {
		return ""
	}
	return *f.SCM
}

// GetCategory returns the Category field if it's non-nil, zero value otherwise.
func (h *HookEvent) GetCategory() string {
	if h == nil || h.Category == nil {
		return ""
	}
	return *h.Category
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (h *HookEvent) GetDescription() string {
	if h == nil || h.Description == nil {
		return ""
	}
	return *h.Description
}

// GetEvent returns the Event field if it's non-nil, zero value otherwise.
func (h *HookEvent) GetEvent() string {
	if h == nil || h.Event == nil {
		return ""
	}
	return *h.Event
}

// GetLabel returns the Label field if it's non-nil, zero value otherwise.
func (h *HookEvent) GetLabel() string {
	if h == nil || h.Label == nil {
		return ""
	}
	return *h.Label
}

// GetRepository returns the Repository field.
func (h *HookEventTypes) GetRepository() *HookEventTypesLinks {
	if h == nil {
		return nil
	}
	return h.Repository
}

// GetTeam returns the Team field.
func (h *HookEventTypes) GetTeam() *HookEventTypesLinks {
	if h == nil {
		return nil
	}
	return h.Team
}

// GetUser returns the User field.
func (h *HookEventTypes) GetUser() *HookEventTypesLinks {
	if h == nil {
		return nil
	}
	return h.User
}

// GetEvents returns the Events field.
func (h *HookEventTypesLinks) GetEvents() *Link {
	if h == nil {
		return nil
	}
	return h.Events
}

// GetAssignee returns the Assignee field.
func (i *Issue) GetAssignee() *User {
	if i == nil {
		return nil
	}
	return i.Assignee
}

// GetComponent returns the Component field.
func (i *Issue) GetComponent() *Component {
	if i == nil {
		return nil
	}
	return i.Component
}

// GetContent returns the Content field.
func (i *Issue) GetContent() *IssueContent {
	if i == nil {
		return nil
	}
	return i.Content
}

// GetCreatedOn returns the CreatedOn field if it's non-nil, zero value otherwise.
func (i *Issue) GetCreatedOn() time.Time {
	if i == nil || i.CreatedOn == nil {
		return time.Time{}
	}
	return *i.CreatedOn
}

// GetEditedOn returns the EditedOn field if it's non-nil, zero value otherwise.
func (i *Issue) GetEditedOn() time.Time {
	if i == nil || i.EditedOn == nil {
		return time.Time{}
	}
	return *i.EditedOn
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (i *Issue) GetID() int64 {
	if i == nil || i.ID == nil {
		return 0
	}
	return *i.ID
}

// GetKind returns the Kind field if it's non-nil, zero value otherwise.
func (i *Issue) GetKind() string {
	if i == nil || i.Kind == nil {
		return ""
	}
	return *i.Kind
}

// GetLinks returns the Links field.
func (i *Issue) GetLinks() *IssueLinks {
	if i == nil {
		return nil
	}
	return i.Links
}

// GetMilestone returns the Milestone field.
func (i *Issue) GetMilestone() *Milestone {
	if i == nil {
		return nil
	}
	return i.Milestone
}

// GetPriority returns the Priority field if it's non-nil, zero value otherwise.
func (i *Issue) GetPriority() string {
	if i == nil || i.Priority == nil {
		return ""
	}
	return *i.Priority
}

// GetReporter returns the Reporter field.
func (i *Issue) GetReporter() *User {
	if i == nil {
		return nil
	}
	return i.Reporter
}

// GetRepository returns the Repository field.
func (i *Issue) GetRepository() *Repository {
	if i == nil {
		return nil
	}
	return i.Repository
}

// GetState returns the State field if it's non-nil, zero value otherwise.
func (i *Issue) GetState() string {
	if i == nil || i.State == nil {
		return ""
	}
	return *i.State
}

// GetTitle returns the Title field if it's non-nil, zero value otherwise.
func (i *Issue) GetTitle() string {
	if i == nil || i.Title == nil {
		return ""
	}
	return *i.Title
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (i *Issue) GetType() string {
	if i == nil || i.Type == nil {
		return ""
	}
	return *i.Type
}

// GetUpdatedOn returns the UpdatedOn field if it's non-nil, zero value otherwise.
func (i *Issue) GetUpdatedOn() time.Time {
	if i == nil || i.UpdatedOn == nil {
		return time.Time{}
	}
	return *i.UpdatedOn
}

// GetVersion returns the Version field.
func (i *Issue) GetVersion() *Version {
	if i == nil {
		return nil
	}
	return i.Version
}

// GetVotes returns the Votes field if it's non-nil, zero value otherwise.
func (i *Issue) GetVotes() int {
	if i == nil || i.Votes == nil {
		return 0
	}
	return *i.Votes
}

// GetWatches returns the Watches field if it's non-nil, zero value otherwise.
func (i *Issue) GetWatches() int {
	if i == nil || i.Watches == nil {
		return 0
	}
	return *i.Watches
}

// GetCreatedOn returns the CreatedOn field if it's non-nil, zero value otherwise.
func (i *IssueChange) GetCreatedOn() time.Time {
	if i == nil || i.CreatedOn == nil {
		return time.Time{}
	}
	return *i.CreatedOn
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (i *IssueChange) GetID() int64 {
	if i == nil || i.ID == nil {
		return 0
	}
	return *i.ID
}

// GetIssue returns the Issue field.
func (i *IssueChange) GetIssue() *Issue {
	if i == nil {
		return nil
	}
	return i.Issue
}

// GetLinks returns the Links field.
func (i *IssueChange) GetLinks() *IssueChangeLinks {
	if i == nil {
		return nil
	}
	return i.Links
}

// GetMessage returns the Message field.
func (i *IssueChange) GetMessage() *Content {
	if i == nil {
		return nil
	}
	return i.Message
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (i *IssueChange) GetType() string {
	if i == nil || i.Type == nil {
		return ""
	}
	return *i.Type
}

// GetUser returns the User field.
func (i *IssueChange) GetUser() *User {
	if i == nil {
		return nil
	}
	return i.User
}

// GetHTML returns the HTML field.
func (i *IssueChangeLinks) GetHTML() *Link {
	if i == nil {
		return nil
	}
	return i.HTML
}

// GetSelf returns the Self field.
func (i *IssueChangeLinks) GetSelf() *Link {
	if i == nil {
		return nil
	}
	return i.Self
}

// GetAssigneeAccountID returns the AssigneeAccountID field if it's non-nil, zero value otherwise.
func (i *IssueChangeRequest) GetAssigneeAccountID() string {
	if i == nil || i.AssigneeAccountID == nil {
		return ""
	}
	return *i.AssigneeAccountID
}

// GetComponent returns the Component field if it's non-nil, zero value otherwise.
func (i *IssueChangeRequest) GetComponent() string {
	if i == nil || i.Component == nil {
		return ""
	}
	return *i.Component
}

// GetContent returns the Content field if it's non-nil, zero value otherwise.
func (i *IssueChangeRequest) GetContent() string {
	if i == nil || i.Content == nil {
		return ""
	}
	return *i.Content
}

// GetKind returns the Kind field if it's non-nil, zero value otherwise.
func (i *IssueChangeRequest) GetKind() string {
	if i == nil || i.Kind == nil {
		return ""
	}
	return *i.Kind
}

// GetMessage returns the Message field if it's non-nil, zero value otherwise.
func (i *IssueChangeRequest) GetMessage() string {
	if i == nil || i.Message == nil {
		return ""
	}
	return *i.Message
}

// GetMilestone returns the Milestone field if it's non-nil, zero value otherwise.
func (i *IssueChangeRequest) GetMilestone() string {
	if i == nil || i.Milestone == nil {
		return ""
	}
	return *i.Milestone
}

// GetPriority returns the Priority field if it's non-nil, zero value otherwise.
func (i *IssueChangeRequest) GetPriority() string {
	if i == nil || i.Priority == nil {
		return ""
	}
	return *i.Priority
}

// GetVersion returns the Version field if it's non-nil, zero value otherwise.
func (i *IssueChangeRequest) GetVersion() string {
	if i == nil || i.Version == nil {
		return ""
	}
	return *i.Version
}

// GetContent returns the Content field.
func (i *IssueComment) GetContent() *Content {
	if i == nil {
		return nil
	}
	return i.Content
}

// GetCreatedOn returns the CreatedOn field if it's non-nil, zero value otherwise.
func (i *IssueComment) GetCreatedOn() time.Time {
	if i == nil || i.CreatedOn == nil {
		return time.Time{}
	}
	return *i.CreatedOn
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (i *IssueComment) GetID() int64 {
	if i == nil || i.ID == nil {
		return 0
	}
	return *i.ID
}

// GetIssue returns the Issue field.
func (i *IssueComment) GetIssue() *Issue {
	if i == nil {
		return nil
	}
	return i.Issue
}

// GetLinks returns the Links field.
func (i *IssueComment) GetLinks() *IssueCommentLinks {
	if i == nil {
		return nil
	}
	return i.Links
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (i *IssueComment) GetType() string {
	if i == nil || i.Type == nil {
		return ""
	}
	return *i.Type
}

// GetUpdatedOn returns the UpdatedOn field if it's non-nil, zero value otherwise.
func (i *IssueComment) GetUpdatedOn() time.Time {
	if i == nil || i.UpdatedOn == nil {
		return time.Time{}
	}
	return *i.UpdatedOn
}

// GetUser returns the User field.
func (i *IssueComment) GetUser() *User {
	if i == nil {
		return nil
	}
	return i.User
}

// GetHTML returns the HTML field.
func (i *IssueCommentLinks) GetHTML() *Link {
	if i == nil {
		return nil
	}
	return i.HTML
}

// GetSelf returns the Self field.
func (i *IssueCommentLinks) GetSelf() *Link {
	if i == nil {
		return nil
	}
	return i.Self
}

// GetContent returns the Content field.
func (i *IssueCommentRequest) GetContent() *Content {
	if i == nil {
		return nil
	}
	return i.Content
}

// GetHTML returns the HTML field if it's non-nil, zero value otherwise.
func (i *IssueContent) GetHTML() string {
	if i == nil || i.HTML == nil {
		return ""
	}
	return *i.HTML
}

// GetMarkup returns the Markup field if it's non-nil, zero value otherwise.
func (i *IssueContent) GetMarkup() string {
	if i == nil || i.Markup == nil {
		return ""
	}
	return *i.Markup
}

// GetRaw returns the Raw field if it's non-nil, zero value otherwise.
func (i *IssueContent) GetRaw() string {
	if i == nil || i.Raw == nil {
		return ""
	}
	return *i.Raw
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (i *IssueContent) GetType() string {
	if i == nil || i.Type == nil {
		return ""
	}
	return *i.Type
}

// GetAttachments returns the Attachments field.
func (i *IssueLinks) GetAttachments() *Link {
	if i == nil {
		return nil
	}
	return i.Attachments
}

// GetComments returns the Comments field.
func (i *IssueLinks) GetComments() *Link {
	if i == nil {
		return nil
	}
	return i.Comments
}

// GetHTML returns the HTML field.
func (i *IssueLinks) GetHTML() *Link {
	if i == nil {
		return nil
	}
	return i.HTML
}

// GetSelf returns the Self field.
func (i *IssueLinks) GetSelf() *Link {
	if i == nil {
		return nil
	}
	return i.Self
}

// GetVote returns the Vote field.
func (i *IssueLinks) GetVote() *Link {
	if i == nil {
		return nil
	}
	return i.Vote
}

// GetWatch returns the Watch field.
func (i *IssueLinks) GetWatch() *Link {
	if i == nil {
		return nil
	}
	return i.Watch
}

// GetAssignee returns the Assignee field.
func (i *IssueRequest) GetAssignee() *IssueRequestAssigneeOpts {
	if i == nil {
		return nil
	}
	return i.Assignee
}

// GetComponent returns the Component field.
func (i *IssueRequest) GetComponent() *ComponentRequest {
	if i == nil {
		return nil
	}
	return i.Component
}

// GetContent returns the Content field.
func (i *IssueRequest) GetContent() *IssueRequestContentOpts {
	if i == nil {
		return nil
	}
	return i.Content
}

// GetKind returns the Kind field if it's non-nil, zero value otherwise.
func (i *IssueRequest) GetKind() string {
	if i == nil || i.Kind == nil {
		return ""
	}
	return *i.Kind
}

// GetMilestone returns the Milestone field.
func (i *IssueRequest) GetMilestone() *MilestoneRequest {
	if i == nil {
		return nil
	}
	return i.Milestone
}

// GetPriority returns the Priority field if it's non-nil, zero value otherwise.
func (i *IssueRequest) GetPriority() string {
	if i == nil || i.Priority == nil {
		return ""
	}
	return *i.Priority
}

// GetTitle returns the Title field if it's non-nil, zero value otherwise.
func (i *IssueRequest) GetTitle() string {
	if i == nil || i.Title == nil {
		return ""
	}
	return *i.Title
}

// GetVersion returns the Version field.
func (i *IssueRequest) GetVersion() *VersionRequest {
	if i == nil {
		return nil
	}
	return i.Version
}

// GetUsername returns the Username field if it's non-nil, zero value otherwise.
func (i *IssueRequestAssigneeOpts) GetUsername() string {
	if i == nil || i.Username == nil {
		return ""
	}
	return *i.Username
}

// GetHTML returns the HTML field if it's non-nil, zero value otherwise.
func (i *IssueRequestContentOpts) GetHTML() string {
	if i == nil || i.HTML == nil {
		return ""
	}
	return *i.HTML
}

// GetRaw returns the Raw field if it's non-nil, zero value otherwise.
func (i *IssueRequestContentOpts) GetRaw() string {
	if i == nil || i.Raw == nil {
		return ""
	}
	return *i.Raw
}

// GetHRef returns the HRef field if it's non-nil, zero value otherwise.
func (l *Link) GetHRef() string {
	if l == nil || l.HRef == nil {
		return ""
	}
	return *l.HRef
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (m *Milestone) GetID() int64 {
	if m == nil || m.ID == nil {
		return 0
	}
	return *m.ID
}

// GetLinks returns the Links field.
func (m *Milestone) GetLinks() *MilestoneLinks {
	if m == nil {
		return nil
	}
	return m.Links
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (m *Milestone) GetName() string {
	if m == nil || m.Name == nil {
		return ""
	}
	return *m.Name
}

// GetRepository returns the Repository field.
func (m *Milestone) GetRepository() *Repository {
	if m == nil {
		return nil
	}
	return m.Repository
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (m *Milestone) GetType() string {
	if m == nil || m.Type == nil {
		return ""
	}
	return *m.Type
}

// GetSelf returns the Self field.
func (m *MilestoneLinks) GetSelf() *Link {
	if m == nil {
		return nil
	}
	return m.Self
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (m *MilestoneRequest) GetName() string {
	if m == nil || m.Name == nil {
		return ""
	}
	return *m.Name
}

// GetNext returns the Next field if it's non-nil, zero value otherwise.
func (p *PaginationInfo) GetNext() string {
	if p == nil || p.Next == nil {
		return ""
	}
	return *p.Next
}

// GetPage returns the Page field if it's non-nil, zero value otherwise.
func (p *PaginationInfo) GetPage() int64 {
	if p == nil || p.Page == nil {
		return 0
	}
	return *p.Page
}

// GetPagelen returns the Pagelen field if it's non-nil, zero value otherwise.
func (p *PaginationInfo) GetPagelen() int64 {
	if p == nil || p.Pagelen == nil {
		return 0
	}
	return *p.Pagelen
}

// GetPrevious returns the Previous field if it's non-nil, zero value otherwise.
func (p *PaginationInfo) GetPrevious() string {
	if p == nil || p.Previous == nil {
		return ""
	}
	return *p.Previous
}

// GetSize returns the Size field if it's non-nil, zero value otherwise.
func (p *PaginationInfo) GetSize() int64 {
	if p == nil || p.Size == nil {
		return 0
	}
	return *p.Size
}

// GetApproved returns the Approved field if it's non-nil, zero value otherwise.
func (p *Participant) GetApproved() bool {
	if p == nil || p.Approved == nil {
		return false
	}
	return *p.Approved
}

// GetParticipatedOn returns the ParticipatedOn field if it's non-nil, zero value otherwise.
func (p *Participant) GetParticipatedOn() time.Time {
	if p == nil || p.ParticipatedOn == nil {
		return time.Time{}
	}
	return *p.ParticipatedOn
}

// GetRole returns the Role field if it's non-nil, zero value otherwise.
func (p *Participant) GetRole() string {
	if p == nil || p.Role == nil {
		return ""
	}
	return *p.Role
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (p *Participant) GetType() string {
	if p == nil || p.Type == nil {
		return ""
	}
	return *p.Type
}

// GetUser returns the User field.
func (p *Participant) GetUser() *User {
	if p == nil {
		return nil
	}
	return p.User
}

// GetApproval returns the Approval field.
func (p *PRActivity) GetApproval() *PRApprovalActivity {
	if p == nil {
		return nil
	}
	return p.Approval
}

// GetPullRequest returns the PullRequest field.
func (p *PRActivity) GetPullRequest() *PullRequest {
	if p == nil {
		return nil
	}
	return p.PullRequest
}

// GetUpdate returns the Update field.
func (p *PRActivity) GetUpdate() *PRUpdateActivity {
	if p == nil {
		return nil
	}
	return p.Update
}

// GetDate returns the Date field if it's non-nil, zero value otherwise.
func (p *PRApprovalActivity) GetDate() time.Time {
	if p == nil || p.Date == nil {
		return time.Time{}
	}
	return *p.Date
}

// GetPullRequest returns the PullRequest field.
func (p *PRApprovalActivity) GetPullRequest() *PullRequest {
	if p == nil {
		return nil
	}
	return p.PullRequest
}

// GetUser returns the User field.
func (p *PRApprovalActivity) GetUser() *User {
	if p == nil {
		return nil
	}
	return p.User
}

// GetDeleted returns the Deleted field if it's non-nil, zero value otherwise.
func (p *PRComment) GetDeleted() bool {
	if p == nil || p.Deleted == nil {
		return false
	}
	return *p.Deleted
}

// GetPullRequest returns the PullRequest field.
func (p *PRComment) GetPullRequest() *PullRequest {
	if p == nil {
		return nil
	}
	return p.PullRequest
}

// GetCloseSourceBranch returns the CloseSourceBranch field if it's non-nil, zero value otherwise.
func (p *PRRequest) GetCloseSourceBranch() bool {
	if p == nil || p.CloseSourceBranch == nil {
		return false
	}
	return *p.CloseSourceBranch
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (p *PRRequest) GetDescription() string {
	if p == nil || p.Description == nil {
		return ""
	}
	return *p.Description
}

// GetDestination returns the Destination field.
func (p *PRRequest) GetDestination() *PRRequestDestinationOpts {
	if p == nil {
		return nil
	}
	return p.Destination
}

// GetSource returns the Source field.
func (p *PRRequest) GetSource() *PRRequestSourceOpts {
	if p == nil {
		return nil
	}
	return p.Source
}

// GetTitle returns the Title field if it's non-nil, zero value otherwise.
func (p *PRRequest) GetTitle() string {
	if p == nil || p.Title == nil {
		return ""
	}
	return *p.Title
}

// GetBranch returns the Branch field.
func (p *PRRequestDestinationOpts) GetBranch() *Branch {
	if p == nil {
		return nil
	}
	return p.Branch
}

// GetUUID returns the UUID field if it's non-nil, zero value otherwise.
func (p *PRRequestReviewerOpts) GetUUID() string {
	if p == nil || p.UUID == nil {
		return ""
	}
	return *p.UUID
}

// GetBranch returns the Branch field.
func (p *PRRequestSourceOpts) GetBranch() *Branch {
	if p == nil {
		return nil
	}
	return p.Branch
}

// GetAuthor returns the Author field.
func (p *PRUpdateActivity) GetAuthor() *User {
	if p == nil {
		return nil
	}
	return p.Author
}

// GetDate returns the Date field if it's non-nil, zero value otherwise.
func (p *PRUpdateActivity) GetDate() time.Time {
	if p == nil || p.Date == nil {
		return time.Time{}
	}
	return *p.Date
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (p *PRUpdateActivity) GetDescription() string {
	if p == nil || p.Description == nil {
		return ""
	}
	return *p.Description
}

// GetDestination returns the Destination field.
func (p *PRUpdateActivity) GetDestination() *PullRequestBranch {
	if p == nil {
		return nil
	}
	return p.Destination
}

// GetReason returns the Reason field if it's non-nil, zero value otherwise.
func (p *PRUpdateActivity) GetReason() string {
	if p == nil || p.Reason == nil {
		return ""
	}
	return *p.Reason
}

// GetSource returns the Source field.
func (p *PRUpdateActivity) GetSource() *PullRequestBranch {
	if p == nil {
		return nil
	}
	return p.Source
}

// GetState returns the State field if it's non-nil, zero value otherwise.
func (p *PRUpdateActivity) GetState() string {
	if p == nil || p.State == nil {
		return ""
	}
	return *p.State
}

// GetTitle returns the Title field if it's non-nil, zero value otherwise.
func (p *PRUpdateActivity) GetTitle() string {
	if p == nil || p.Title == nil {
		return ""
	}
	return *p.Title
}

// GetAuthor returns the Author field.
func (p *PullRequest) GetAuthor() *User {
	if p == nil {
		return nil
	}
	return p.Author
}

// GetBody returns the Body field.
func (p *PullRequest) GetBody() *PullRequestBody {
	if p == nil {
		return nil
	}
	return p.Body
}

// GetClosedBy returns the ClosedBy field.
func (p *PullRequest) GetClosedBy() *User {
	if p == nil {
		return nil
	}
	return p.ClosedBy
}

// GetCloseSourceBranch returns the CloseSourceBranch field if it's non-nil, zero value otherwise.
func (p *PullRequest) GetCloseSourceBranch() bool {
	if p == nil || p.CloseSourceBranch == nil {
		return false
	}
	return *p.CloseSourceBranch
}

// GetCommentCount returns the CommentCount field if it's non-nil, zero value otherwise.
func (p *PullRequest) GetCommentCount() int64 {
	if p == nil || p.CommentCount == nil {
		return 0
	}
	return *p.CommentCount
}

// GetCreatedOn returns the CreatedOn field if it's non-nil, zero value otherwise.
func (p *PullRequest) GetCreatedOn() time.Time {
	if p == nil || p.CreatedOn == nil {
		return time.Time{}
	}
	return *p.CreatedOn
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (p *PullRequest) GetDescription() string {
	if p == nil || p.Description == nil {
		return ""
	}
	return *p.Description
}

// GetDestination returns the Destination field.
func (p *PullRequest) GetDestination() *PullRequestBranch {
	if p == nil {
		return nil
	}
	return p.Destination
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (p *PullRequest) GetID() int64 {
	if p == nil || p.ID == nil {
		return 0
	}
	return *p.ID
}

// GetLinks returns the Links field.
func (p *PullRequest) GetLinks() *PullRequestLinks {
	if p == nil {
		return nil
	}
	return p.Links
}

// GetMergeCommit returns the MergeCommit field if it's non-nil, zero value otherwise.
func (p *PullRequest) GetMergeCommit() string {
	if p == nil || p.MergeCommit == nil {
		return ""
	}
	return *p.MergeCommit
}

// GetReason returns the Reason field if it's non-nil, zero value otherwise.
func (p *PullRequest) GetReason() string {
	if p == nil || p.Reason == nil {
		return ""
	}
	return *p.Reason
}

// GetSource returns the Source field.
func (p *PullRequest) GetSource() *PullRequestBranch {
	if p == nil {
		return nil
	}
	return p.Source
}

// GetState returns the State field if it's non-nil, zero value otherwise.
func (p *PullRequest) GetState() string {
	if p == nil || p.State == nil {
		return ""
	}
	return *p.State
}

// GetSummary returns the Summary field.
func (p *PullRequest) GetSummary() *Content {
	if p == nil {
		return nil
	}
	return p.Summary
}

// GetTaskCount returns the TaskCount field if it's non-nil, zero value otherwise.
func (p *PullRequest) GetTaskCount() int64 {
	if p == nil || p.TaskCount == nil {
		return 0
	}
	return *p.TaskCount
}

// GetTitle returns the Title field if it's non-nil, zero value otherwise.
func (p *PullRequest) GetTitle() string {
	if p == nil || p.Title == nil {
		return ""
	}
	return *p.Title
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (p *PullRequest) GetType() string {
	if p == nil || p.Type == nil {
		return ""
	}
	return *p.Type
}

// GetUpdatedOn returns the UpdatedOn field if it's non-nil, zero value otherwise.
func (p *PullRequest) GetUpdatedOn() string {
	if p == nil || p.UpdatedOn == nil {
		return ""
	}
	return *p.UpdatedOn
}

// GetDescription returns the Description field.
func (p *PullRequestBody) GetDescription() *Content {
	if p == nil {
		return nil
	}
	return p.Description
}

// GetTitle returns the Title field.
func (p *PullRequestBody) GetTitle() *Content {
	if p == nil {
		return nil
	}
	return p.Title
}

// GetBranch returns the Branch field.
func (p *PullRequestBranch) GetBranch() *Branch {
	if p == nil {
		return nil
	}
	return p.Branch
}

// GetCommit returns the Commit field.
func (p *PullRequestBranch) GetCommit() *Commit {
	if p == nil {
		return nil
	}
	return p.Commit
}

// GetRepository returns the Repository field.
func (p *PullRequestBranch) GetRepository() *Repository {
	if p == nil {
		return nil
	}
	return p.Repository
}

// GetActivity returns the Activity field.
func (p *PullRequestLinks) GetActivity() *Link {
	if p == nil {
		return nil
	}
	return p.Activity
}

// GetApprove returns the Approve field.
func (p *PullRequestLinks) GetApprove() *Link {
	if p == nil {
		return nil
	}
	return p.Approve
}

// GetComments returns the Comments field.
func (p *PullRequestLinks) GetComments() *Link {
	if p == nil {
		return nil
	}
	return p.Comments
}

// GetCommits returns the Commits field.
func (p *PullRequestLinks) GetCommits() *Link {
	if p == nil {
		return nil
	}
	return p.Commits
}

// GetDecline returns the Decline field.
func (p *PullRequestLinks) GetDecline() *Link {
	if p == nil {
		return nil
	}
	return p.Decline
}

// GetDiff returns the Diff field.
func (p *PullRequestLinks) GetDiff() *Link {
	if p == nil {
		return nil
	}
	return p.Diff
}

// GetHTML returns the HTML field.
func (p *PullRequestLinks) GetHTML() *Link {
	if p == nil {
		return nil
	}
	return p.HTML
}

// GetMerge returns the Merge field.
func (p *PullRequestLinks) GetMerge() *Link {
	if p == nil {
		return nil
	}
	return p.Merge
}

// GetSelf returns the Self field.
func (p *PullRequestLinks) GetSelf() *Link {
	if p == nil {
		return nil
	}
	return p.Self
}

// GetStatuses returns the Statuses field.
func (p *PullRequestLinks) GetStatuses() *Link {
	if p == nil {
		return nil
	}
	return p.Statuses
}

// GetDate returns the Date field if it's non-nil, zero value otherwise.
func (r *Ref) GetDate() time.Time {
	if r == nil || r.Date == nil {
		return time.Time{}
	}
	return *r.Date
}

// GetDefaultMergeStrategy returns the DefaultMergeStrategy field if it's non-nil, zero value otherwise.
func (r *Ref) GetDefaultMergeStrategy() string {
	if r == nil || r.DefaultMergeStrategy == nil {
		return ""
	}
	return *r.DefaultMergeStrategy
}

// GetLinks returns the Links field.
func (r *Ref) GetLinks() *RefLinks {
	if r == nil {
		return nil
	}
	return r.Links
}

// GetMessage returns the Message field if it's non-nil, zero value otherwise.
func (r *Ref) GetMessage() string {
	if r == nil || r.Message == nil {
		return ""
	}
	return *r.Message
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (r *Ref) GetName() string {
	if r == nil || r.Name == nil {
		return ""
	}
	return *r.Name
}

// GetTarget returns the Target field.
func (r *Ref) GetTarget() *Commit {
	if r == nil {
		return nil
	}
	return r.Target
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (r *Ref) GetType() string {
	if r == nil || r.Type == nil {
		return ""
	}
	return *r.Type
}

// GetCommits returns the Commits field.
func (r *RefLinks) GetCommits() *Link {
	if r == nil {
		return nil
	}
	return r.Commits
}

// GetHTML returns the HTML field.
func (r *RefLinks) GetHTML() *Link {
	if r == nil {
		return nil
	}
	return r.HTML
}

// GetSelf returns the Self field.
func (r *RefLinks) GetSelf() *Link {
	if r == nil {
		return nil
	}
	return r.Self
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (r *RefRequest) GetName() string {
	if r == nil || r.Name == nil {
		return ""
	}
	return *r.Name
}

// GetCreatedOn returns the CreatedOn field if it's non-nil, zero value otherwise.
func (r *Repository) GetCreatedOn() time.Time {
	if r == nil || r.CreatedOn == nil {
		return time.Time{}
	}
	return *r.CreatedOn
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (r *Repository) GetDescription() string {
	if r == nil || r.Description == nil {
		return ""
	}
	return *r.Description
}

// GetForkPolicy returns the ForkPolicy field if it's non-nil, zero value otherwise.
func (r *Repository) GetForkPolicy() string {
	if r == nil || r.ForkPolicy == nil {
		return ""
	}
	return *r.ForkPolicy
}

// GetFullName returns the FullName field if it's non-nil, zero value otherwise.
func (r *Repository) GetFullName() string {
	if r == nil || r.FullName == nil {
		return ""
	}
	return *r.FullName
}

// GetHasIssues returns the HasIssues field if it's non-nil, zero value otherwise.
func (r *Repository) GetHasIssues() bool {
	if r == nil || r.HasIssues == nil {
		return false
	}
	return *r.HasIssues
}

// GetHasWiki returns the HasWiki field if it's non-nil, zero value otherwise.
func (r *Repository) GetHasWiki() bool {
	if r == nil || r.HasWiki == nil {
		return false
	}
	return *r.HasWiki
}

// GetIsPrivate returns the IsPrivate field if it's non-nil, zero value otherwise.
func (r *Repository) GetIsPrivate() bool {
	if r == nil || r.IsPrivate == nil {
		return false
	}
	return *r.IsPrivate
}

// GetLanguage returns the Language field if it's non-nil, zero value otherwise.
func (r *Repository) GetLanguage() string {
	if r == nil || r.Language == nil {
		return ""
	}
	return *r.Language
}

// GetLinks returns the Links field.
func (r *Repository) GetLinks() *RepositoryLinks {
	if r == nil {
		return nil
	}
	return r.Links
}

// GetMainBranch returns the MainBranch field.
func (r *Repository) GetMainBranch() *RepositoryMainBranch {
	if r == nil {
		return nil
	}
	return r.MainBranch
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (r *Repository) GetName() string {
	if r == nil || r.Name == nil {
		return ""
	}
	return *r.Name
}

// GetOwner returns the Owner field.
func (r *Repository) GetOwner() *User {
	if r == nil {
		return nil
	}
	return r.Owner
}

// GetParent returns the Parent field.
func (r *Repository) GetParent() *Repository {
	if r == nil {
		return nil
	}
	return r.Parent
}

// GetSCM returns the SCM field if it's non-nil, zero value otherwise.
func (r *Repository) GetSCM() string {
	if r == nil || r.SCM == nil {
		return ""
	}
	return *r.SCM
}

// GetSize returns the Size field if it's non-nil, zero value otherwise.
func (r *Repository) GetSize() int64 {
	if r == nil || r.Size == nil {
		return 0
	}
	return *r.Size
}

// GetSlug returns the Slug field if it's non-nil, zero value otherwise.
func (r *Repository) GetSlug() string {
	if r == nil || r.Slug == nil {
		return ""
	}
	return *r.Slug
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (r *Repository) GetType() string {
	if r == nil || r.Type == nil {
		return ""
	}
	return *r.Type
}

// GetUpdatedOn returns the UpdatedOn field if it's non-nil, zero value otherwise.
func (r *Repository) GetUpdatedOn() time.Time {
	if r == nil || r.UpdatedOn == nil {
		return time.Time{}
	}
	return *r.UpdatedOn
}

// GetWebsite returns the Website field if it's non-nil, zero value otherwise.
func (r *Repository) GetWebsite() string {
	if r == nil || r.Website == nil {
		return ""
	}
	return *r.Website
}

// GetHRef returns the HRef field if it's non-nil, zero value otherwise.
func (r *RepositoryCloneLink) GetHRef() string {
	if r == nil || r.HRef == nil {
		return ""
	}
	return *r.HRef
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (r *RepositoryCloneLink) GetName() string {
	if r == nil || r.Name == nil {
		return ""
	}
	return *r.Name
}

// GetActive returns the Active field if it's non-nil, zero value otherwise.
func (r *RepositoryHook) GetActive() bool {
	if r == nil || r.Active == nil {
		return false
	}
	return *r.Active
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (r *RepositoryHook) GetCreatedAt() time.Time {
	if r == nil || r.CreatedAt == nil {
		return time.Time{}
	}
	return *r.CreatedAt
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (r *RepositoryHook) GetDescription() string {
	if r == nil || r.Description == nil {
		return ""
	}
	return *r.Description
}

// GetURL returns the URL field if it's non-nil, zero value otherwise.
func (r *RepositoryHook) GetURL() string {
	if r == nil || r.URL == nil {
		return ""
	}
	return *r.URL
}

// GetUUID returns the UUID field if it's non-nil, zero value otherwise.
func (r *RepositoryHook) GetUUID() string {
	if r == nil || r.UUID == nil {
		return ""
	}
	return *r.UUID
}

// GetActive returns the Active field if it's non-nil, zero value otherwise.
func (r *RepositoryHookRequest) GetActive() bool {
	if r == nil || r.Active == nil {
		return false
	}
	return *r.Active
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (r *RepositoryHookRequest) GetDescription() string {
	if r == nil || r.Description == nil {
		return ""
	}
	return *r.Description
}

// GetURL returns the URL field if it's non-nil, zero value otherwise.
func (r *RepositoryHookRequest) GetURL() string {
	if r == nil || r.URL == nil {
		return ""
	}
	return *r.URL
}

// GetAvatar returns the Avatar field.
func (r *RepositoryLinks) GetAvatar() *Link {
	if r == nil {
		return nil
	}
	return r.Avatar
}

// GetBranches returns the Branches field.
func (r *RepositoryLinks) GetBranches() *Link {
	if r == nil {
		return nil
	}
	return r.Branches
}

// GetCommits returns the Commits field.
func (r *RepositoryLinks) GetCommits() *Link {
	if r == nil {
		return nil
	}
	return r.Commits
}

// GetDownloads returns the Downloads field.
func (r *RepositoryLinks) GetDownloads() *Link {
	if r == nil {
		return nil
	}
	return r.Downloads
}

// GetForks returns the Forks field.
func (r *RepositoryLinks) GetForks() *Link {
	if r == nil {
		return nil
	}
	return r.Forks
}

// GetHTML returns the HTML field.
func (r *RepositoryLinks) GetHTML() *Link {
	if r == nil {
		return nil
	}
	return r.HTML
}

// GetPullRequests returns the PullRequests field.
func (r *RepositoryLinks) GetPullRequests() *Link {
	if r == nil {
		return nil
	}
	return r.PullRequests
}

// GetSelf returns the Self field.
func (r *RepositoryLinks) GetSelf() *Link {
	if r == nil {
		return nil
	}
	return r.Self
}

// GetSource returns the Source field.
func (r *RepositoryLinks) GetSource() *Link {
	if r == nil {
		return nil
	}
	return r.Source
}

// GetTags returns the Tags field.
func (r *RepositoryLinks) GetTags() *Link {
	if r == nil {
		return nil
	}
	return r.Tags
}

// GetWatchers returns the Watchers field.
func (r *RepositoryLinks) GetWatchers() *Link {
	if r == nil {
		return nil
	}
	return r.Watchers
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (r *RepositoryMainBranch) GetName() string {
	if r == nil || r.Name == nil {
		return ""
	}
	return *r.Name
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (r *RepositoryMainBranch) GetType() string {
	if r == nil || r.Type == nil {
		return ""
	}
	return *r.Type
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (r *RepositoryRequest) GetDescription() string {
	if r == nil || r.Description == nil {
		return ""
	}
	return *r.Description
}

// GetForkPolicy returns the ForkPolicy field if it's non-nil, zero value otherwise.
func (r *RepositoryRequest) GetForkPolicy() string {
	if r == nil || r.ForkPolicy == nil {
		return ""
	}
	return *r.ForkPolicy
}

// GetHasIssues returns the HasIssues field if it's non-nil, zero value otherwise.
func (r *RepositoryRequest) GetHasIssues() bool {
	if r == nil || r.HasIssues == nil {
		return false
	}
	return *r.HasIssues
}

// GetHasWiki returns the HasWiki field if it's non-nil, zero value otherwise.
func (r *RepositoryRequest) GetHasWiki() bool {
	if r == nil || r.HasWiki == nil {
		return false
	}
	return *r.HasWiki
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (r *RepositoryRequest) GetName() string {
	if r == nil || r.Name == nil {
		return ""
	}
	return *r.Name
}

// GetSCM returns the SCM field if it's non-nil, zero value otherwise.
func (r *RepositoryRequest) GetSCM() string {
	if r == nil || r.SCM == nil {
		return ""
	}
	return *r.SCM
}

// GetRepositories returns the Repositories field.
func (s *SearchCodeFileLinks) GetRepositories() *Link {
	if s == nil {
		return nil
	}
	return s.Repositories
}

// GetSelf returns the Self field.
func (s *SearchCodeFileLinks) GetSelf() *Link {
	if s == nil {
		return nil
	}
	return s.Self
}

// GetContentMatchCount returns the ContentMatchCount field if it's non-nil, zero value otherwise.
func (s *SearchCodeResult) GetContentMatchCount() int64 {
	if s == nil || s.ContentMatchCount == nil {
		return 0
	}
	return *s.ContentMatchCount
}

// GetFile returns the File field.
func (s *SearchCodeResult) GetFile() *CodeFile {
	if s == nil {
		return nil
	}
	return s.File
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (s *SearchCodeResult) GetType() string {
	if s == nil || s.Type == nil {
		return ""
	}
	return *s.Type
}

// GetQuerySubstituted returns the QuerySubstituted field if it's non-nil, zero value otherwise.
func (s *SearchCodeResults) GetQuerySubstituted() bool {
	if s == nil || s.QuerySubstituted == nil {
		return false
	}
	return *s.QuerySubstituted
}

// GetValues returns the Values field.
func (s *SearchCodeResults) GetValues() *SearchCodeResult {
	if s == nil {
		return nil
	}
	return s.Values
}

// GetLines returns the Lines field.
func (s *SearchContentMatch) GetLines() *SearchContentMatchLine {
	if s == nil {
		return nil
	}
	return s.Lines
}

// GetLine returns the Line field if it's non-nil, zero value otherwise.
func (s *SearchContentMatchLine) GetLine() int64 {
	if s == nil || s.Line == nil {
		return 0
	}
	return *s.Line
}

// GetMatch returns the Match field if it's non-nil, zero value otherwise.
func (s *SearchMatch) GetMatch() bool {
	if s == nil || s.Match == nil {
		return false
	}
	return *s.Match
}

// GetText returns the Text field if it's non-nil, zero value otherwise.
func (s *SearchMatch) GetText() string {
	if s == nil || s.Text == nil {
		return ""
	}
	return *s.Text
}

// GetCommit returns the Commit field.
func (s *SRCMetadata) GetCommit() *Commit {
	if s == nil {
		return nil
	}
	return s.Commit
}

// GetLinks returns the Links field.
func (s *SRCMetadata) GetLinks() *FileHistoryLinks {
	if s == nil {
		return nil
	}
	return s.Links
}

// GetMimetype returns the Mimetype field if it's non-nil, zero value otherwise.
func (s *SRCMetadata) GetMimetype() string {
	if s == nil || s.Mimetype == nil {
		return ""
	}
	return *s.Mimetype
}

// GetPath returns the Path field if it's non-nil, zero value otherwise.
func (s *SRCMetadata) GetPath() string {
	if s == nil || s.Path == nil {
		return ""
	}
	return *s.Path
}

// GetSize returns the Size field if it's non-nil, zero value otherwise.
func (s *SRCMetadata) GetSize() int64 {
	if s == nil || s.Size == nil {
		return 0
	}
	return *s.Size
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (s *SRCMetadata) GetType() string {
	if s == nil || s.Type == nil {
		return ""
	}
	return *s.Type
}

// GetKey returns the Key field if it's non-nil, zero value otherwise.
func (s *SSHKeyAddRequest) GetKey() string {
	if s == nil || s.Key == nil {
		return ""
	}
	return *s.Key
}

// GetLabel returns the Label field if it's non-nil, zero value otherwise.
func (s *SSHKeyAddRequest) GetLabel() string {
	if s == nil || s.Label == nil {
		return ""
	}
	return *s.Label
}

// GetAccountStatus returns the AccountStatus field if it's non-nil, zero value otherwise.
func (t *Team) GetAccountStatus() string {
	if t == nil || t.AccountStatus == nil {
		return ""
	}
	return *t.AccountStatus
}

// GetCreatedOn returns the CreatedOn field if it's non-nil, zero value otherwise.
func (t *Team) GetCreatedOn() time.Time {
	if t == nil || t.CreatedOn == nil {
		return time.Time{}
	}
	return *t.CreatedOn
}

// GetDisplayName returns the DisplayName field if it's non-nil, zero value otherwise.
func (t *Team) GetDisplayName() string {
	if t == nil || t.DisplayName == nil {
		return ""
	}
	return *t.DisplayName
}

// GetHas2FAEnabled returns the Has2FAEnabled field if it's non-nil, zero value otherwise.
func (t *Team) GetHas2FAEnabled() string {
	if t == nil || t.Has2FAEnabled == nil {
		return ""
	}
	return *t.Has2FAEnabled
}

// GetLinks returns the Links field.
func (t *Team) GetLinks() *TeamLinks {
	if t == nil {
		return nil
	}
	return t.Links
}

// GetNickname returns the Nickname field if it's non-nil, zero value otherwise.
func (t *Team) GetNickname() string {
	if t == nil || t.Nickname == nil {
		return ""
	}
	return *t.Nickname
}

// GetUsername returns the Username field if it's non-nil, zero value otherwise.
func (t *Team) GetUsername() string {
	if t == nil || t.Username == nil {
		return ""
	}
	return *t.Username
}

// GetUUID returns the UUID field if it's non-nil, zero value otherwise.
func (t *Team) GetUUID() string {
	if t == nil || t.UUID == nil {
		return ""
	}
	return *t.UUID
}

// GetWebsite returns the Website field if it's non-nil, zero value otherwise.
func (t *Team) GetWebsite() string {
	if t == nil || t.Website == nil {
		return ""
	}
	return *t.Website
}

// GetAvatar returns the Avatar field.
func (t *TeamLinks) GetAvatar() *Link {
	if t == nil {
		return nil
	}
	return t.Avatar
}

// GetFollowers returns the Followers field.
func (t *TeamLinks) GetFollowers() *Link {
	if t == nil {
		return nil
	}
	return t.Followers
}

// GetFollowing returns the Following field.
func (t *TeamLinks) GetFollowing() *Link {
	if t == nil {
		return nil
	}
	return t.Following
}

// GetHooks returns the Hooks field.
func (t *TeamLinks) GetHooks() *Link {
	if t == nil {
		return nil
	}
	return t.Hooks
}

// GetHTML returns the HTML field.
func (t *TeamLinks) GetHTML() *Link {
	if t == nil {
		return nil
	}
	return t.HTML
}

// GetMembers returns the Members field.
func (t *TeamLinks) GetMembers() *Link {
	if t == nil {
		return nil
	}
	return t.Members
}

// GetProjects returns the Projects field.
func (t *TeamLinks) GetProjects() *Link {
	if t == nil {
		return nil
	}
	return t.Projects
}

// GetRepositories returns the Repositories field.
func (t *TeamLinks) GetRepositories() *Link {
	if t == nil {
		return nil
	}
	return t.Repositories
}

// GetSelf returns the Self field.
func (t *TeamLinks) GetSelf() *Link {
	if t == nil {
		return nil
	}
	return t.Self
}

// GetSnippets returns the Snippets field.
func (t *TeamLinks) GetSnippets() *Link {
	if t == nil {
		return nil
	}
	return t.Snippets
}

// GetPermission returns the Permission field if it's non-nil, zero value otherwise.
func (t *TeamPermission) GetPermission() string {
	if t == nil || t.Permission == nil {
		return ""
	}
	return *t.Permission
}

// GetTeam returns the Team field.
func (t *TeamPermission) GetTeam() *Team {
	if t == nil {
		return nil
	}
	return t.Team
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (t *TeamPermission) GetType() string {
	if t == nil || t.Type == nil {
		return ""
	}
	return *t.Type
}

// GetUser returns the User field.
func (t *TeamPermission) GetUser() *User {
	if t == nil {
		return nil
	}
	return t.User
}

// GetCreatedOn returns the CreatedOn field if it's non-nil, zero value otherwise.
func (t *TeamProject) GetCreatedOn() time.Time {
	if t == nil || t.CreatedOn == nil {
		return time.Time{}
	}
	return *t.CreatedOn
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (t *TeamProject) GetDescription() string {
	if t == nil || t.Description == nil {
		return ""
	}
	return *t.Description
}

// GetIsPrivate returns the IsPrivate field if it's non-nil, zero value otherwise.
func (t *TeamProject) GetIsPrivate() bool {
	if t == nil || t.IsPrivate == nil {
		return false
	}
	return *t.IsPrivate
}

// GetKey returns the Key field if it's non-nil, zero value otherwise.
func (t *TeamProject) GetKey() string {
	if t == nil || t.Key == nil {
		return ""
	}
	return *t.Key
}

// GetLinks returns the Links field.
func (t *TeamProject) GetLinks() *TeamProjectLinks {
	if t == nil {
		return nil
	}
	return t.Links
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (t *TeamProject) GetName() string {
	if t == nil || t.Name == nil {
		return ""
	}
	return *t.Name
}

// GetOwner returns the Owner field.
func (t *TeamProject) GetOwner() *User {
	if t == nil {
		return nil
	}
	return t.Owner
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (t *TeamProject) GetType() string {
	if t == nil || t.Type == nil {
		return ""
	}
	return *t.Type
}

// GetUpdatedOn returns the UpdatedOn field if it's non-nil, zero value otherwise.
func (t *TeamProject) GetUpdatedOn() time.Time {
	if t == nil || t.UpdatedOn == nil {
		return time.Time{}
	}
	return *t.UpdatedOn
}

// GetUUID returns the UUID field if it's non-nil, zero value otherwise.
func (t *TeamProject) GetUUID() string {
	if t == nil || t.UUID == nil {
		return ""
	}
	return *t.UUID
}

// GetAvatar returns the Avatar field.
func (t *TeamProjectLinks) GetAvatar() *Link {
	if t == nil {
		return nil
	}
	return t.Avatar
}

// GetHTML returns the HTML field.
func (t *TeamProjectLinks) GetHTML() *Link {
	if t == nil {
		return nil
	}
	return t.HTML
}

// GetSelf returns the Self field.
func (t *TeamProjectLinks) GetSelf() *Link {
	if t == nil {
		return nil
	}
	return t.Self
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (t *TeamProjectRequest) GetDescription() string {
	if t == nil || t.Description == nil {
		return ""
	}
	return *t.Description
}

// GetIsPrivate returns the IsPrivate field if it's non-nil, zero value otherwise.
func (t *TeamProjectRequest) GetIsPrivate() bool {
	if t == nil || t.IsPrivate == nil {
		return false
	}
	return *t.IsPrivate
}

// GetKey returns the Key field if it's non-nil, zero value otherwise.
func (t *TeamProjectRequest) GetKey() string {
	if t == nil || t.Key == nil {
		return ""
	}
	return *t.Key
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (t *TeamProjectRequest) GetName() string {
	if t == nil || t.Name == nil {
		return ""
	}
	return *t.Name
}

// GetPermission returns the Permission field if it's non-nil, zero value otherwise.
func (t *TeamRepoPermission) GetPermission() string {
	if t == nil || t.Permission == nil {
		return ""
	}
	return *t.Permission
}

// GetRepository returns the Repository field.
func (t *TeamRepoPermission) GetRepository() *Repository {
	if t == nil {
		return nil
	}
	return t.Repository
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (t *TeamRepoPermission) GetType() string {
	if t == nil || t.Type == nil {
		return ""
	}
	return *t.Type
}

// GetUser returns the User field.
func (t *TeamRepoPermission) GetUser() *User {
	if t == nil {
		return nil
	}
	return t.User
}

// GetAccountID returns the AccountID field if it's non-nil, zero value otherwise.
func (u *User) GetAccountID() string {
	if u == nil || u.AccountID == nil {
		return ""
	}
	return *u.AccountID
}

// GetAccountStatus returns the AccountStatus field if it's non-nil, zero value otherwise.
func (u *User) GetAccountStatus() string {
	if u == nil || u.AccountStatus == nil {
		return ""
	}
	return *u.AccountStatus
}

// GetCreatedOn returns the CreatedOn field if it's non-nil, zero value otherwise.
func (u *User) GetCreatedOn() time.Time {
	if u == nil || u.CreatedOn == nil {
		return time.Time{}
	}
	return *u.CreatedOn
}

// GetDisplayName returns the DisplayName field if it's non-nil, zero value otherwise.
func (u *User) GetDisplayName() string {
	if u == nil || u.DisplayName == nil {
		return ""
	}
	return *u.DisplayName
}

// GetIsStaff returns the IsStaff field if it's non-nil, zero value otherwise.
func (u *User) GetIsStaff() bool {
	if u == nil || u.IsStaff == nil {
		return false
	}
	return *u.IsStaff
}

// GetLinks returns the Links field.
func (u *User) GetLinks() *UserLinks {
	if u == nil {
		return nil
	}
	return u.Links
}

// GetLocation returns the Location field if it's non-nil, zero value otherwise.
func (u *User) GetLocation() string {
	if u == nil || u.Location == nil {
		return ""
	}
	return *u.Location
}

// GetNickname returns the Nickname field if it's non-nil, zero value otherwise.
func (u *User) GetNickname() string {
	if u == nil || u.Nickname == nil {
		return ""
	}
	return *u.Nickname
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (u *User) GetType() string {
	if u == nil || u.Type == nil {
		return ""
	}
	return *u.Type
}

// GetUsername returns the Username field if it's non-nil, zero value otherwise.
func (u *User) GetUsername() string {
	if u == nil || u.Username == nil {
		return ""
	}
	return *u.Username
}

// GetUUID returns the UUID field if it's non-nil, zero value otherwise.
func (u *User) GetUUID() string {
	if u == nil || u.UUID == nil {
		return ""
	}
	return *u.UUID
}

// GetWebsite returns the Website field if it's non-nil, zero value otherwise.
func (u *User) GetWebsite() string {
	if u == nil || u.Website == nil {
		return ""
	}
	return *u.Website
}

// GetEmail returns the Email field if it's non-nil, zero value otherwise.
func (u *UserEmail) GetEmail() string {
	if u == nil || u.Email == nil {
		return ""
	}
	return *u.Email
}

// GetIsConfirmed returns the IsConfirmed field if it's non-nil, zero value otherwise.
func (u *UserEmail) GetIsConfirmed() bool {
	if u == nil || u.IsConfirmed == nil {
		return false
	}
	return *u.IsConfirmed
}

// GetIsPrimary returns the IsPrimary field if it's non-nil, zero value otherwise.
func (u *UserEmail) GetIsPrimary() bool {
	if u == nil || u.IsPrimary == nil {
		return false
	}
	return *u.IsPrimary
}

// GetLinks returns the Links field.
func (u *UserEmail) GetLinks() *UserEmailLinks {
	if u == nil {
		return nil
	}
	return u.Links
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (u *UserEmail) GetType() string {
	if u == nil || u.Type == nil {
		return ""
	}
	return *u.Type
}

// GetSelf returns the Self field.
func (u *UserEmailLinks) GetSelf() *Link {
	if u == nil {
		return nil
	}
	return u.Self
}

// GetActive returns the Active field if it's non-nil, zero value otherwise.
func (u *UserHook) GetActive() bool {
	if u == nil || u.Active == nil {
		return false
	}
	return *u.Active
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (u *UserHook) GetCreatedAt() time.Time {
	if u == nil || u.CreatedAt == nil {
		return time.Time{}
	}
	return *u.CreatedAt
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (u *UserHook) GetDescription() string {
	if u == nil || u.Description == nil {
		return ""
	}
	return *u.Description
}

// GetSubjectType returns the SubjectType field if it's non-nil, zero value otherwise.
func (u *UserHook) GetSubjectType() string {
	if u == nil || u.SubjectType == nil {
		return ""
	}
	return *u.SubjectType
}

// GetURL returns the URL field if it's non-nil, zero value otherwise.
func (u *UserHook) GetURL() string {
	if u == nil || u.URL == nil {
		return ""
	}
	return *u.URL
}

// GetUUID returns the UUID field if it's non-nil, zero value otherwise.
func (u *UserHook) GetUUID() string {
	if u == nil || u.UUID == nil {
		return ""
	}
	return *u.UUID
}

// GetAvatar returns the Avatar field.
func (u *UserLinks) GetAvatar() *Link {
	if u == nil {
		return nil
	}
	return u.Avatar
}

// GetFollowers returns the Followers field.
func (u *UserLinks) GetFollowers() *Link {
	if u == nil {
		return nil
	}
	return u.Followers
}

// GetFollowing returns the Following field.
func (u *UserLinks) GetFollowing() *Link {
	if u == nil {
		return nil
	}
	return u.Following
}

// GetHooks returns the Hooks field.
func (u *UserLinks) GetHooks() *Link {
	if u == nil {
		return nil
	}
	return u.Hooks
}

// GetHTML returns the HTML field.
func (u *UserLinks) GetHTML() *Link {
	if u == nil {
		return nil
	}
	return u.HTML
}

// GetRepositories returns the Repositories field.
func (u *UserLinks) GetRepositories() *Link {
	if u == nil {
		return nil
	}
	return u.Repositories
}

// GetSelf returns the Self field.
func (u *UserLinks) GetSelf() *Link {
	if u == nil {
		return nil
	}
	return u.Self
}

// GetSnippets returns the Snippets field.
func (u *UserLinks) GetSnippets() *Link {
	if u == nil {
		return nil
	}
	return u.Snippets
}

// GetPermission returns the Permission field if it's non-nil, zero value otherwise.
func (u *UserRepositoriesPermission) GetPermission() string {
	if u == nil || u.Permission == nil {
		return ""
	}
	return *u.Permission
}

// GetRepository returns the Repository field.
func (u *UserRepositoriesPermission) GetRepository() *Repository {
	if u == nil {
		return nil
	}
	return u.Repository
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (u *UserRepositoriesPermission) GetType() string {
	if u == nil || u.Type == nil {
		return ""
	}
	return *u.Type
}

// GetUser returns the User field.
func (u *UserRepositoriesPermission) GetUser() *User {
	if u == nil {
		return nil
	}
	return u.User
}

// GetComment returns the Comment field if it's non-nil, zero value otherwise.
func (u *UsersSSHKey) GetComment() string {
	if u == nil || u.Comment == nil {
		return ""
	}
	return *u.Comment
}

// GetCreatedOn returns the CreatedOn field if it's non-nil, zero value otherwise.
func (u *UsersSSHKey) GetCreatedOn() time.Time {
	if u == nil || u.CreatedOn == nil {
		return time.Time{}
	}
	return *u.CreatedOn
}

// GetKey returns the Key field if it's non-nil, zero value otherwise.
func (u *UsersSSHKey) GetKey() string {
	if u == nil || u.Key == nil {
		return ""
	}
	return *u.Key
}

// GetLabel returns the Label field if it's non-nil, zero value otherwise.
func (u *UsersSSHKey) GetLabel() string {
	if u == nil || u.Label == nil {
		return ""
	}
	return *u.Label
}

// GetLastUsed returns the LastUsed field if it's non-nil, zero value otherwise.
func (u *UsersSSHKey) GetLastUsed() time.Time {
	if u == nil || u.LastUsed == nil {
		return time.Time{}
	}
	return *u.LastUsed
}

// GetLinks returns the Links field.
func (u *UsersSSHKey) GetLinks() *UsersSSHKeyLinks {
	if u == nil {
		return nil
	}
	return u.Links
}

// GetOwner returns the Owner field.
func (u *UsersSSHKey) GetOwner() *User {
	if u == nil {
		return nil
	}
	return u.Owner
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (u *UsersSSHKey) GetType() string {
	if u == nil || u.Type == nil {
		return ""
	}
	return *u.Type
}

// GetUUID returns the UUID field if it's non-nil, zero value otherwise.
func (u *UsersSSHKey) GetUUID() string {
	if u == nil || u.UUID == nil {
		return ""
	}
	return *u.UUID
}

// GetSelf returns the Self field.
func (u *UsersSSHKeyLinks) GetSelf() *Link {
	if u == nil {
		return nil
	}
	return u.Self
}

// GetPermission returns the Permission field if it's non-nil, zero value otherwise.
func (u *UserTeamsPermission) GetPermission() string {
	if u == nil || u.Permission == nil {
		return ""
	}
	return *u.Permission
}

// GetTeam returns the Team field.
func (u *UserTeamsPermission) GetTeam() *Team {
	if u == nil {
		return nil
	}
	return u.Team
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (u *UserTeamsPermission) GetType() string {
	if u == nil || u.Type == nil {
		return ""
	}
	return *u.Type
}

// GetUser returns the User field.
func (u *UserTeamsPermission) GetUser() *User {
	if u == nil {
		return nil
	}
	return u.User
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (v *Version) GetID() int64 {
	if v == nil || v.ID == nil {
		return 0
	}
	return *v.ID
}

// GetLinks returns the Links field.
func (v *Version) GetLinks() *VersionLinks {
	if v == nil {
		return nil
	}
	return v.Links
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (v *Version) GetName() string {
	if v == nil || v.Name == nil {
		return ""
	}
	return *v.Name
}

// GetRepository returns the Repository field.
func (v *Version) GetRepository() *Repository {
	if v == nil {
		return nil
	}
	return v.Repository
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (v *Version) GetType() string {
	if v == nil || v.Type == nil {
		return ""
	}
	return *v.Type
}

// GetSelf returns the Self field.
func (v *VersionLinks) GetSelf() *Link {
	if v == nil {
		return nil
	}
	return v.Self
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (v *VersionRequest) GetName() string {
	if v == nil || v.Name == nil {
		return ""
	}
	return *v.Name
}
