name: ci
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2

      - name: Cache go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Run go vet
        run: go vet ./...
      
      - name: Check gofmt diff
        run: |
          gofmt -d -s $(find . -name '*.go' |grep -v vendor)
          git diff --exit-code; code=$?; git checkout -- .; (exit $code)

      - name: Ensure go run gen-accessors produces a zero diff
        shell: bash
        run: |
          cd bitbucket
          go run gen-accessors.go
          git diff --exit-code; code=$?; git checkout -- .; (exit $code)